img_size: 384
patch_size: 4
in_chans: 3
embed_dim: 128
depths: [ 2, 2, 18, 2 ]
num_heads: [ 4, 8, 16, 32 ]
drop_path_rate: 0.1
window_size: 12
use_checkpoint: True
mask_patch_size: 32
mask_ratio: 0.5
num_classes: 0