model_name: 'vit'
img_size: 224
embed_dim: 768
depth: 12
num_heads: 12
use_abs_pos_emb: False
use_rel_pos_bias: False
use_shared_rel_pos_bias: True
use_mean_pooling: False
mask_patch_size: 32
mask_ratio: 0.6
drop_path_rate: 0.1
patch_size: 16
num_classes: 0